version: '3.1'
services:
    mariadb:
        container_name: file_explorer_db
        image: 'mariadb'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mariadb
        ports:
            - '39004:3306'

    webserver:
        container_name: file_explorer_webserver
        image: 'nginx:alpine'
        working_dir: /application
        hostname: file-explorer.local
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '39001:80'

    php-fpm:
        container_name: file_explorer_app
        build:
            context: ./phpdocker/php-fpm/
        working_dir: /application
        ports:
            - '7501:7500'
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
